package com.restapi.scoregoat.domain;

import lombok.AllArgsConstructor;
import lombok.Getter;

@AllArgsConstructor
@Getter
public enum Code {
    SEASON_CLEAN_ERROR("E001"),
    SEASON_SET_DB_ERROR("E002"),
    SESSION_REFRESH_ERROR("E003"),
    LOGIN_RESET_ATTEMPT_ERROR("E004"),
    FIXTURE_GET_ERROR("E005"),
    MATCH_UPLOAD_ERROR("E006"),
    MATCH_UPLOAD_ALL_ERROR("E007"),
    EXECUTE_PREDICTION_ERROR("E008"),
    EXECUTION_GRADUATION_ERROR("E009"),

    SEASON_SET("I001"),
    USER_CREATE("I002"),
    USER_LOGIN("I003"),
    LOGIN_LOCKED_DATES_UPDATE("I004"),
    SESSION_EXPIRED_REMOVE("I005"),
    USER_ACCOUNT_INFO_CHSNGE("I006"),
    USER_PASSWORD_CHANGED("I007"),
    UPLOAD_MATCHES_OK("I008"),
    UPLOAD_ALL_MATCHES_OK("I009"),
    SAVE_ALL_PREDICTIONS("I010"),
    USER_DELETE("I011"),
    ASSIGN_RANKS("I012");

    private final String code;
}
